schema = 3

[mod]
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."github.com/labstack/echo/v4"]
    version = "v4.14.0"
    hash = "sha256-i07IB+C7kvbwwhnE9olN75LR9l2qDNYCengVYo9pjO0="
  [mod."github.com/labstack/gommon"]
    version = "v0.4.2"
    hash = "sha256-395+BETDpv15L2lsCiEccwakXgEQxKHlYBAU0Ot3qhY="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.14"
    hash = "sha256-JC60PjKj7MvhZmUHTZ9p372FV72I9Mxvli3fivTbxuA="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.23.2"
    hash = "sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.2"
    hash = "sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ="
  [mod."github.com/prometheus/common"]
    version = "v0.66.1"
    hash = "sha256-bqHPaV9IV70itx63wqwgy2PtxMN0sn5ThVxDmiD7+Tk="
  [mod."github.com/prometheus/procfs"]
    version = "v0.16.1"
    hash = "sha256-OBCvKlLW2obct35p0L9Q+1ZrxZjpTmbgHMP2rng9hpo="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."github.com/valyala/fasttemplate"]
    version = "v1.2.2"
    hash = "sha256-gp+lNXE8zjO+qJDM/YbS6V43HFsYP6PKn4ux1qa5lZ0="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.2"
    hash = "sha256-oC8RWdf1zbMYCtmR0ATy/kCkhIwPR9UqFZSMOKLVF/A="
  [mod."golang.org/x/crypto"]
    version = "v0.46.0"
    hash = "sha256-I8N/spcw3/h0DFA+V1WK38HctckWIB9ep93DEVCALxU="
  [mod."golang.org/x/net"]
    version = "v0.48.0"
    hash = "sha256-oZpddsiJwWCH3Aipa+XXpy7G/xHY5fEagUSok7T0bXE="
  [mod."golang.org/x/sys"]
    version = "v0.39.0"
    hash = "sha256-dxTBu/JAWUkPbjFIXXRFdhQWyn+YyEpIC+tWqGo0Y6U="
  [mod."golang.org/x/text"]
    version = "v0.32.0"
    hash = "sha256-9PXtWBKKY9rG4AgjSP4N+I1DhepXhy8SF/vWSIDIoWs="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.8"
    hash = "sha256-yZN8ZON0b5HjUNUSubHst7zbvnMsOzd81tDPYQRtPgM="
